- name: default
  kind: postgres
  configuration:
    connection_info:
      database_url:
        from_env: HASURA_GRAPHQL_DATABASE_URL
      isolation_level: read-committed
      pool_settings:
        connection_lifetime: 600
        idle_timeout: 180
        max_connections: 50
        retries: 1
      use_prepared_statements: true
  tables:
  - table:
      name: workspaces
      schema: public
  - table:
      name: profiles
      schema: public
  - table:
      name: workspace_users
      schema: public
  - table:
      name: social_accounts
      schema: public
  - table:
      name: media_assets
      schema: public
  - table:
      name: tags
      schema: public
  - table:
      name: posts
      schema: public
  - table:
      name: post_destinations
      schema: public
  - table:
      name: post_tags
      schema: public
  - table:
      name: post_media
      schema: public
  functions: []
